N=32;
L=1;
i=0;
A=stiffness(N);
F=rightterm(N);
u=linsolve(full(A),full(F));
u=sparse(u);
u1=u(1:N^2,1);
u2=u(N^2+1:2*N^2,1);
phi=u(2*N^2+1:3*N^2,1);
clear A F I
phi=reshape(phi,[N,N])';
phi=[zeros(N,1) phi];
phi=[zeros(1,N+1);phi];
u1=reshape(u1,[N,N])';
u1=[zeros(N,1) u1];
u1=[zeros(1,N+1);u1];
u2=reshape(u2,[N,N])';
u2=[zeros(N,1) u2];
u2=[zeros(1,N+1);u2];
phi=full(phi);
u1=full(u1);
u2=full(u2);
x=linspace(0,L,N+1);
y=linspace(0,L,N+1);
[x,y]=meshgrid(x,y);
e1=sum((u1-x.*y).^2,"all")+sum((u2-x.*y).^2,"all");%error of displacement
e2=sum((phi-x.*y).^2,"all");%error of eletrical potential